### ISSUE TITLE
Descriptor Indexing Issue in Check

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/SMQTK#330]
```
 DEBUG - 2018-02-01 15:45:29,882 - smqtk.utils.plugin.getPlugins[smqtk.representation.descriptor_index].get_plugins - [smqtk.representation.descriptor_index.postgres] Checking attribute 'itertools'
  DEBUG - 2018-02-01 15:45:29,882 - smqtk.utils.plugin.getPlugins[smqtk.representation.descriptor_index].get_plugins - [smqtk.representation.descriptor_index.postgres] Checking attribute 'logging'
  DEBUG - 2018-02-01 15:45:29,882 - smqtk.utils.plugin.getPlugins[smqtk.representation.descriptor_index].get_plugins - [smqtk.representation.descriptor_index.postgres] Checking attribute 'norm_psql_cmd_string'
  DEBUG - 2018-02-01 15:45:29,882 - smqtk.utils.plugin.getPlugins[smqtk.representation.descriptor_index].get_plugins - [smqtk.representation.descriptor_index.postgres] Checking attribute 'pickle'
  DEBUG - 2018-02-01 15:45:29,882 - smqtk.utils.plugin.getPlugins[smqtk.representation.descriptor_index].get_plugins - [smqtk.representation.descriptor_index.postgres] Checking attribute 'psycopg2'
   INFO - 2018-02-01 15:45:29,885 - smqtk.bin.train_itq.main - Using UUIDs from loaded DescriptorIndex (count=21)
   INFO - 2018-02-01 15:45:29,885 - smqtk.bin.train_itq.main - Fitting ITQ model
Traceback (most recent call last):
  File "/home/matt/Dev/viame/build/install/bin/train_itq", line 11, in <module>
    load_entry_point('smqtk==0.7.0', 'console_scripts', 'train_itq')()
  File "/home/matt/Dev/viame/build/install/lib/python2.7/site-packages/smqtk/bin/train_itq.py", line 74, in main
    functor.fit(d_iter)
  File "/home/matt/Dev/viame/build/install/lib/python2.7/site-packages/smqtk/algorithms/nn_index/lsh/functors/itq.py", line 322, in fit
    if len(descriptors[0].vector()) < self.bit_length:
  File "/home/matt/Dev/viame/build/install/lib/python2.7/site-packages/smqtk/representation/descriptor_index/__init__.py", line 29, in __getitem__
    return self.get_descriptor(uuid)
  File "/home/matt/Dev/viame/build/install/lib/python2.7/site-packages/smqtk/representation/descriptor_index/postgres.py", line 520, in get_descriptor
    r = list(self._single_execute(eh, True))
  File "/home/matt/Dev/viame/build/install/lib/python2.7/site-packages/smqtk/representation/descriptor_index/postgres.py", line 284, in _single_execute
    execute_hook(cur)
  File "/home/matt/Dev/viame/build/install/lib/python2.7/site-packages/smqtk/representation/descriptor_index/postgres.py", line 514, in eh
    raise KeyError(uuid)
KeyError: 0
  DEBUG - 2018-02-01
```

for

if len(descriptors[0].vector()) < self.bit_length: in itq.py

**Comment by Purg** [comment]
This issue should be fixed with the v0.8.0 release. Now the input `descriptors` parameter is checked if a `Sequence` instance, which a `DescriptorIndex` is not. The conversion to a list should now be correctly triggered.
