### ISSUE TITLE
Fix ball tree script

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/SMQTK#331]
```
  INFO - 2018-02-01 15:53:41,632 - smqtk.bin.make_balltree.main - Initializing ball tree
Traceback (most recent call last):
  File "/home/matt/Dev/viame/build/install/bin/make_balltree", line 11, in <module>
    load_entry_point('smqtk==0.7.0', 'console_scripts', 'make_balltree')()
  File "/home/matt/Dev/viame/build/install/lib/python2.7/site-packages/smqtk/bin/make_balltree.py", line 62, in main
    btree = SkLearnBallTreeHashIndex(balltree_model_fp, leaf_size, rand_seed)
  File "/home/matt/Dev/viame/build/install/lib/python2.7/site-packages/smqtk/algorithms/nn_index/hash_index/sklearn_balltree.py", line 112, in __init__
    self.load_model()
  File "/home/matt/Dev/viame/build/install/lib/python2.7/site-packages/smqtk/algorithms/nn_index/hash_index/sklearn_balltree.py", line 160, in load_model
    if self.cache_element and not self.cache_element.is_empty():
AttributeError: 'str' object has no attribute 'is_empty'
```

Element being passed as data type not file path

**Comment by Purg** [comment]
This should be resolved with the new v0.8.0 version as the make_balltree now uses the common configuration pattern instead of assuming input parameters directly on the command-line.
